# Generated by Django 4.2.4 on 2023-08-30 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_time", models.DateTimeField(editable=False)),
                ("updated_time", models.DateTimeField()),
                ("product_name", models.CharField(max_length=50)),
                ("selling_price", models.FloatField(default=0)),
                ("discounted_price", models.FloatField(default=0)),
                ("description", models.TextField()),
                ("quantity", models.CharField(blank=True, max_length=1000, null=True)),
                ("ingredients", models.TextField(default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Curd", "Curd"),
                            ("Milk", "Milk"),
                            ("Paneer", "Paneer"),
                            ("Ghee", "Ghee"),
                            ("Kulfi", "Kulfi"),
                            ("Ice", "Ice-Creams"),
                            ("Milkshake", "Milkshake"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prod_image", models.ImageField(upload_to="prod_img")),
            ],
            options={"abstract": False,},
        ),
    ]
