# Generated by Django 4.2.4 on 2023-08-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecom_app", "0002_alter_product_creation_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="ingredients", new_name="composition",
        ),
    ]
