# Generated by Django 4.2.4 on 2023-09-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0003_profile_city_profile_locality_profile_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="locality", new_name="landmark",
        ),
    ]
