# Generated by Django 4.2.4 on 2023-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0004_rename_locality_profile_landmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pincode",
            field=models.TextField(blank=True, null=True),
        ),
    ]
